### ISSUE TITLE
Consider adding ddev-get label so it's discoverable

### ISSUE THREAD

**Issue by rfay** [JanoPL/ddev-kibana#10]
Would you consider adding the `ddev-get` label to make this discoverable? Somebody was just asking for Kibana the other day.

**Comment by JanoPL** [comment]
I already checked and there is a ```ddev-get``` label in the repo and a listing in the unofficial addons list.

or is missing label somewhere else and not showing correctly on the list?

**Comment by rfay** [comment]
Sorry, guess I'm blind. I think it was because you have all those other labels :)

**Comment by rfay** [comment]
Oh, maybe I got confused by looking at it on an issue page, where the labels are about the issues.

**Comment by rfay** [comment]
When you think it's ready, it can be promoted to the ddev namespace. I see some old obsolete things like the `version` tag in the docker-compose.yaml, but I imagine this is working well for you!

**Comment by rfay** [comment]
Also I think this depends on elasticsearch, right? DDEV add-ons now support dependency checking.

**Comment by JanoPL** [comment]
I think we can promote it to the official namespace, and I can change the composer file version to be cross-compatible.

But you mentioned dependency checking. It’s something required in the config file for add-ons to fire a trigger with a warning that this add-on requires the elasticsearch add-on.

**Comment by rfay** [comment]
See https://ddev.readthedocs.io/en/latest/users/extend/additional-services/#sections-and-features-of-ddev-get-add-on-installyaml - may be good to review that stuff too since there are some new features in v1.22+
