### ISSUE TITLE
Error after adding Kibana

### ISSUE THREAD

**Issue by Firesphere** [JanoPL/ddev-kibana#21]
Ran `ddev get ddev/ddev-elasticsearch`
Ran `ddev get JanoPL/ddev-kibana`
Ran `ddev restart`

Got:

failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: `error getting credentials - err: docker-credential-osxkeychain resolves to executable in current directory (./docker-credential-osxkeychain), out: ``` 
Failed to restart elastic: docker-compose build failed: composeCmd failed to run 'COMPOSE_PROJECT_NAME=ddev-elastic docker-compose -f /Users/firesphere/Projects/elastic/.ddev/.ddev-docker-compose-full.yaml --progress=quiet build', action='[--progress=quiet build]', err='exit status 17', stdout='', stderr='failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: `error getting credentials - err: docker-credential-osxkeychain resolves to executable in current directory (./docker-credential-osxkeychain), out: ```', output='', stderr='failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exit status 1, out: `error getting credentials - err: docker-credential-osxkeychain resolves to executable in current directory (./docker-credential-osxkeychain), out: ```'

**Comment by rfay** [comment]
This is a Docker failure. Please remove the references to docker-credential-xxx from your ~/.docker.

From what you've shown this has nothing to do with this add-on.

**Comment by rfay** [comment]
Note that Docker has had an outage all day, but you may want to delete your ~/.docker/config.json or at least the line about docker-credential-xxx

**Comment by Firesphere** [comment]
It throws the error when adding Kibana, nowhere else really...

```
cat ~/.docker/config.json
{
	"auths": {},
	"credsStore": "desktop",
	"currentContext": "colima"
}
```
and
```
cat ~/.docker/daemon.json 
{
	"builder": { "gc": { "defaultKeepStorage": "20GB", "enabled": true } },
	"experimental": false,
	"features": { "buildkit": true }
}
```

have no mention of docker-credential-xxx, nor am I, or have I, logged in with Docker anywhere (as far as I am aware)

**Comment by rfay** [comment]
You have it somewhere :)

But this may be related to today's ongoing docker outage. https://www.dockerstatus.com/

**Comment by rfay** [comment]
You definitely shouldn't have `	"credsStore": "desktop",` if you're using colima. Just delete the config.json. It will be recreated.

**Comment by rfay** [comment]
Kibana has a build stage in it that depends on hub.docker.com, https://github.com/JanoPL/ddev-kibana/blob/95099bd9cbbee00d6ab6b18800bbd85f7bc1bbf9/docker-compose.kibana.yaml#L6-L8

You likely aren't doing anything else right now that needs anything but your existing images and build cache. 

A new project may have the same class of problem.

**Comment by Firesphere** [comment]
Okay, removing `.docker/config.json`, restarting Colima, and, apparently, re-downloading images, seems to have fixed the problem for now.

Indeed most probably related to the Docker Hub problems.

**Comment by rfay** [comment]
Please close then, thanks.
