### ISSUE TITLE
🐛 BUG: Service NOT available on HTTPS

### ISSUE THREAD

**Issue by tyler36** [JanoPL/ddev-kibana#3]
Documents state:

> You can access the Kibana server directly from the host by visiting https://<projectname>.ddev.site:5601

This accessing `https://<projectname>.ddev.site:5601` geneartes an "ERR_SSL_PROTOCOL_ERROR" error in Chrome.
However, service appears to be `http://<projectname>.ddev.site:5601` (HTTP only).

**Comment by JanoPL** [comment]
Thanks for noticing, this is typo in the readme, it should be ```http:// ```

At the beginning i considered about add possibility to use both protocol HTTP and HTTPS, to adding encrypted communication not only between web browser and kibana but also between elastic search and kibana, something similar to production environment

but configuration encrypted TLS required configure a communication for both kibana and elastic search host.

when I have some free time, I'll take care of it

**Comment by tyler36** [comment]
I'm new to ElasticSearch and Kibana so I'm not really sure if #4 works in all situations. 

Addons like this one (`janpl/ddev-kibana`) are great at letting me explore new software. Thanks for making the addon!
